theme: minima
title: "CESAR GODOY DELAIGUE"
description: "Data Analysis + Visualization"
baseurl: "/"
url: "https://tuusuario.github.io"
author:
  name: "Cesar Godoy Delaigue"
  email: "tuemail@ejemplo.com"
social_links:
  twitter: "https://twitter.com/tuusuario"
  github: "https://github.com/tuusuario"
  linkedin: "https://www.linkedin.com/in/tuusuario/"
markdown: kramdown
highlighter: rouge

# Enlace a tu archivo de estilos personalizados
include: ["assets/css/styles.css"]



