title: "CESAR GODOY DELAIGUE"
description: "Visualizaciones y Análisis de Datos"
baseurl: ""  # Déjalo vacío si estás usando un repositorio de usuario
url: "https://godoca2.github.io"
theme: minima  # O cualquier tema de Jekyll que prefieras
author:
  name: "Cesar Godoy Delaigue"
  email: "cgodoy.delaigue@gmail.com"
markdown: kramdown
highlighter: rouge




