theme: minima
title: "CESAR GODOY DELAIGUE"
description: "Data Analyst + Visualization"
baseurl: "/"  # Mantén esto en '/' para indicar que está en la raíz

markdown: kramdown
highlighter: rouge
include: ["assets/css/styles.css"]





