theme: jekyll-theme-minimal  # Puedes cambiar este tema por cualquier otro tema soportado por GitHub Pages
title: César Godoy Delaigue Homepage  # Cambia esto por el título que quieras
description: Visualizaciones de Datos  # Cambia esto por la descripción que desees
